/*
 * LogicConstants.h
 *
 *  Created on: Aug 27, 2015
 *      Author: jairo-mm
 */

#ifndef LOGIC_LOGICCONSTANTS_H_
#define LOGIC_LOGICCONSTANTS_H_

class LogicConstants {
public:
	LogicConstants();
	virtual ~LogicConstants();
protected:

	int PATOCOLORADO = 1;

	int TARROCANELO = 2;

	int PATOSALVAJE = 3;

	int YAGUASAPIQUIRROJO = 4;

	int GANSODEHAWAI = 5;

	int VIDAPATOCOLORADO = 5;

	int VIDATARROCANELO = 1;

	int VIDAYAGUASAPIQUIRROJO = 1;

	int VIDAGANSODEHAWAI = 2;

	int VIDAPATOSALVAJE = 1;

	int PUNTOSPATOCOLORADO = 10;

	int PUNTOSTARROCANELO;

	int PUNTOSPATOSALVAJE;

	int PUNTOSYAGUASAPIQUIRROJO;

	int PUNTOSGANSODEHAWAI;

	float PROBABILIDADINICIALPATOCOLORADO = 0.05;

	float PROBABILIDADINICIALTARROCANELO = 0.82;

	float PROBABILIDADINICIALPATOSALVAJE = 0.02;

	float PROBABILIDADINICIALYAGUASAPIQUIRROJO = 0.01;

	float PROBABILIDADINICIALGANSODEHAWAI = 0.1;

	float AUMENTOPROBABILIDAD = 0.01;

	int POSICIONYINICIAL = 100;

	int LONGITUDPANTALLA = 1250;

	int ANCHOPANTALLA = 700;

	int VELOCIDADPATOCOLORADO = 5;

	int VELOCIDADYAGUASAPIQUIRROJO = 10;

	int VELOCIDADTARROCANELO = 1;

	int VELOCIDADGANSODEHAWAI_PATOSALVAJE = 3;

	int LONGITUDIMAGENPATO = 80;

	int LONGITUDPANTALLAEFECTIVA = 1170;
};

#endif /* LOGIC_LOGICCONSTANTS_H_ */
